# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Clean White v0.2 by Naah"
license = "Apache"

licenselink = "https://github.com/naah69/hugo-theme-cleanwhite/blob/master/LICENSE"
description = "A clean, elegant blog theme for hugo"
homepage = "https://github.com/naah69/hugo-theme-cleanwhite"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.2

[author]
  name = "Naah"
  homepage = "https://github.com/naah69"

# If porting an existing theme
[original]
  name = "Naah Blog"
  homepage = "http://www.naah69.com/"
