# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Art White"
license = "Apache"

licenselink = "https://github.com/naah69/hugo-theme-artwhite/blob/master/LICENSE"
description = "A simple and art blog theme for hugo"
homepage = "https://github.com/naah69/hugo-theme-artwhite"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.1

[author]
  name = "Naah"
  homepage = "https://github.com/naah69"

# If porting an existing theme
[original]
  name = "hugo-theme-artwhite"
  author = "zhaohuabing"
  homepage = "https://zhaohuabing.com/"
  repo = "https://github.com/zhaohuabing/hugo-theme-artwhite"
